Updated tools and expanded Helm chart
hpi-schul-cloud/infra-otc-cert-manager-webhook pull request #2
Opened 2024-06-17 14:04 UTC by Jaybee18

# Description

The purpose of this pull request is mainly to improve the security of the project.

## Links to Tickets or other pull requests

## Changes

The PR updates multiple used modules as well as the go version of the project to remove CVE findings.
It also makes sure that the docker container does not run as root and updates the Dockerfile and the Helm Chart accordingly.

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-06-25 12:56 UTC, Jaybee18 commented
Hey @bischofmax @mamutmk5,

It seems that the original author of this repo, @MarkusBartels, is no longer active.
Can someone else please have a look at this pull request?

2024-06-25 13:08 UTC, mamutmk5 commented
> Hey @bischofmax @mamutmk5,
> 
> It seems that the original author of this repo, @MarkusBartels, is no longer active. Can someone else please have a look at this pull request?

Hi @Jaybee18 thank you for your pr. Yes the original author is not more active. I have assigned and inform the Team who is in charge of it.

2024-06-25 13:27 UTC, Jaybee18 commented
Thank you!

2024-07-22 12:56 UTC, Jaybee18 commented
Hello @hpi-schul-cloud/sre-team,

I would like to just check in with you and ask for a status update.
Are you currently working on this or is there maybe an estimate when you can start working on this pr?

2024-07-23 09:53 UTC, aimee-889 commented
Hello [Jaybee18](https://github.com/Jaybee18) :) Thank you much for the PR. We plan to review it, but we are a bit short on manpower at the moment. We added it to our To Do List and hope to be able to review it soon.

2024-07-24 14:33 UTC, dimapin requested changes
Thank you for your PR @Jaybee18. Can you please add the "properties" parameter to the README.md.

2024-07-24 14:33 UTC, dimapin commented on Dockerfile
> +FROM alpine:3.20.0
For base images we define only major and minor versions to have an updated version on a new build

2024-08-12 14:08 UTC, dimapin approved these changes

2024-08-12 14:08 UTC, merged